tennisblock/availability/urls.py
from django.urls import path

from .views import (AvailabilityView, AvailabilityAngularView, AvailabilityFormView)

app_name = 'availability'
urlpatterns = (
    path('', AvailabilityView.as_view(), name="main"),
    path(r'angular/', AvailabilityAngularView.as_view(), name="angular"),
    path('availability_form/', AvailabilityFormView.as_view(), name='form'),
    path('availability_form/<int:pk>/', AvailabilityFormView.as_view(), name='form-post'),
)

tennisblock/members/urls.py
from django.urls import re_path

from .views import (MembersView, MembersViewAngular, MembersViewReact,
                    PlayerListView, PlayerDetailView,
                    PlayerUpdateView, PlayerDeleteView,
                    PlayerCreateView, SeasonPlayerFormView,
                    SeasonPlayerUpdate)

app_name = 'members'
urlpatterns = [
    re_path(r'^$', MembersViewReact.as_view(), name='block_react'),
    re_path(r'^blockmembers/$', MembersView.as_view(), name='block'),
    re_path(r'^form/$', SeasonPlayerFormView.as_view(), name='members_form'),
    re_path(r'^update/$', SeasonPlayerUpdate.as_view(), name='members_update'),
    re_path(r'^player/list/$', PlayerListView.as_view(), name='player_list'),
    re_path(r"^player/create/$", PlayerCreateView.as_view(), name="player_create"),
    re_path(r'^player/(?P<pk>\d+)/detail/$', PlayerDetailView.as_view(), name='player_detail'),
    re_path(r'^player/(?P<pk>\d+)/update/$', PlayerUpdateView.as_view(), name='player_update'),
    re_path(r'^player/(?P<pk>\d+)/delete/$', PlayerDeleteView.as_view(), name='player_delete'),
    re_path(r'^add/$', PlayerCreateView.as_view(), name='addplayer'),
]

tennisblock/season/urls.py
from django.urls import re_path, path

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

from .views import (
    SeasonsView,
    SeasonDetailView,
    SeasonCreate,
    CouplesView
)

app_name = 'season'
urlpatterns = [
    re_path(r'^$', SeasonsView.as_view(), name="seasons"),
    re_path(r'^(?P<pk>\d+)/$',
            SeasonDetailView.as_view(), name="season_detail"),
    re_path(r'^create/',
            SeasonCreate.as_view(), name='create_season'),
    path('<int:pk>/couples/',
         CouplesView.as_view(), name="couple_editor")
]

tennisblock/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from views import *

urlpatterns = patterns('',
               # Examples:
               url(r'^$', HomeView.as_view(), name='home'),
               url(r'^schedule/notify/(?P<date>\d{4}-\d{1,2}-\d{1,2})/?',
                   ScheduleNotify.as_view(),name="schedule_notify"),
               url(r'^schedule/', BlockSchedule.as_view(),name='schedule'),
               url(r'^availability/', AvailabilityView.as_view(),
                   name='availability'),

               url(r'^api/', include('tennisblock.api.urls')),
               url(r'^playsheet/', PlaysheetView.as_view()),
               url(r'^members/', include('tennisblock.members.urls')),
               url(r'^contact/?', ContactView.as_view(),name="contact"),
               url(r'^about/?', AboutView.as_view(),name="about"),
               url(r'^accounts/', include('tennisblock.accounts.urls')),
               url(r'^seasons/$', SeasonsView.as_view(),name="seasons"),
               url(r'^seasons/(?P<pk>\d+)/$', SeasonsView.as_view(),name="season_view"),
               url(r'^couples/(?P<pk>\d+)/$', CouplesView.as_view(),name="couple_editor"),

               # Uncomment the next line to enable the admin:
               url(r'^kag3hewb/', include(admin.site.urls)),
       )

tennisblock/webapp/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views as auth_views

from wagtail.core import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls

from .views import (
    HomeView,
    AvailabilityView,
    AvailabilityFormView,
    PlaysheetView,
    ContactView,
    AboutView,
)

urlpatterns = [
    path('confirmation/', include('confirm.urls', namespace='confirmation')),
    path('', auth_views.LoginView.as_view(
        template_name='login.html',
        redirect_authenticated_user=True),
         name='login'),
    path('availability/', include('availability.urls', namespace='availability')),
    path('playsheet/', PlaysheetView.as_view()),
    path('accounts/', include('accounts.urls')),
    path('contact/', ContactView.as_view(), name="contact"),
    path('season/', include('season.urls')),
    path('members/', include('members.urls')),
    path('schedule/', include('schedule.urls', namespace='schedule')),
    path('api/', include('api.urls')),
    path('django-admin/', admin.site.urls),
    path('chat/', include('tennis_channels.urls', namespace='chat')),

    path('admin/', include(wagtailadmin_urls)),
    path('', include(wagtail_urls)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

tennisblock/webapp/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class ContactForm(forms.Form):
    email = forms.EmailField(max_length=100,
                             required=True,
                             label=_('Please enter your e-mail address.'),
                             widget=forms.EmailInput({
                                 'id': 'bootstrap-email',
                             }))
    message = forms.CharField(max_length=500,
                              required=True,
                              label=_('Enter your message'),
                              widget=forms.Textarea({
                                  'id': 'bootstrap-message',
                                  'cols': '60', 'rows': '10'})
                              )


class AvailabilityForm(forms.Form):
    name = forms.CharField(label=_('Player name'), )
    # availability = forms.BooleanField(required=False)

tennisblock/webapp/views.py
from django.views.generic import TemplateView
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin

from django.forms.formsets import (
    formset_factory, BaseFormSet)

from django import forms
from django.shortcuts import render
from django.conf import settings

from TBLib.view import TennisLoginView
from .forms import ContactForm

from .forms import AvailabilityForm
from TBLib.view import class_login_required


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "home.html"


@class_login_required
class AvailabilityView(TemplateView):
    template_name = "availability.html"


class AvailabilityFormSet(BaseFormSet):
    def add_fields(self, form, index):
        super(AvailabilityFormSet, self).add_fields(form, index)
        form.field_list = []
        for x in range(12):
            f = forms.BooleanField(required=False, label='')
            field_nm = "avail_{}".format(x)
            form.fields[field_nm] = f
            form.field_list.append(field_nm)


class AvailabilityFormView(TemplateView):
    template_name = "availability_form.html"
    thankyou_template = "thankyou.html"

    def _get_formset(self, data=None):
        """ Create the formset object """
        fs = formset_factory(AvailabilityForm, extra=31, formset=AvailabilityFormSet)
        initial_data = [{'name': 'Billy Bob'}]
        if data:
            return fs(data=data, initial=initial_data)
        return fs(initial=initial_data)

    def get(self, request, **kwargs):
        context = self.get_context_data(**kwargs)
        context['formset'] = self._get_formset()

        return render(request, self.template_name, context)

    def post(self, request):
        context = self.get_context_data()
        fs = self._get_formset(data=request.POST)

        if fs.is_valid():
            print("Valid Formset!")

            return render(request,
                          self.thankyou_template,
                          context)
        else:
            print("Form is invalid")
            context['formset'] = fs
            return render(request, self.template_name, context)


class PlaysheetView(TennisLoginView):
    template_name = "playsheet.html"


class AboutView(TemplateView):
    template_name = "about.html"


class ContactView(TemplateView):
    template_name = "contact.html"
    thankyou_template = "thankyou.html"

    def get(self, request):
        form = ContactForm()
        return render(request,
                      self.template_name,
                      {'form': form}
                      )

    def post(self, request):
        form = ContactForm(request.POST)

        if form.is_valid():
            from_email = settings.CONTACT_US_EMAIL
            recipient_list = settings.CONTACT_FORM_RECIPIENTS

            sender_email = form.cleaned_data['email']
            message = form.cleaned_data['message']

            message = "FROM: %s\n\n\nMESSAGE:\n\n%s" % (sender_email, message)

            subject = settings.CONTACT_US_SUBJECT

            send_mail(subject, message, from_email, recipient_list)

            return render(request, self.thankyou_template)

        return render(request, self.template_name, {'form': form})

tennisblock/webapp/templates/common/angular_base.html
{% extends "site_base.html" %}
{% load static %}
{% load i18n %}
{% load gbtags %}

{% block angular_script %}
    <!-- site_base.html: angular_script -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.11/angular.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.11/angular-route.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.11/angular-resource.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.11/angular-cookies.min.js"></script>

    <script type="text/javascript" src="{% static 'js/angular/apps/tennisblock.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/angular/services/factories.js' %}"> </script>
    <script type="text/javascript" src="{% static 'js/angular/services/services.js' %}"></script>

{% endblock %}

tennisblock/webapp/templates/common/base.html
{% load staticfiles %}
{% load i18n %}
{% load gbtags %}
{% load compress %}

<!DOCTYPE HTML>

<html lang="{{ LANGUAGE_CODE }}" ng-app="{{ angularapp }}" class="main">
    <head>
        <link rel="icon" href="{% static 'img/favicon.png' %}">
        <meta name="viewport" content="width=device-width, width=device-width, initial-scale=1.0">

        {% block style_base %}
            <!-- base.html: style_base -->
            <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
            <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
            {% block extra_style %}{% endblock %}
        {% endblock %}

        {% block head_script %}
            <!-- base.html: head_script -->
        {% endblock %}

        {% block page_style %}
            <!-- base.html: page_style -->
        {% endblock %}

        {% block less_engine %}
            <!-- base.html: less_engine -->
            {% if USE_LESS %}
                <!-- less enabled -->
                <script type="text/javascript">
                  less = {
                    env: "development",
                    async: false,
                    fileAsync: false,
                    poll: {{ LESS_POLL }},
                    dumpLineNumbers: "comments",
                    relativeUrls: false
                  };
                </script>
                <script src="//cdnjs.cloudflare.com/ajax/libs/less.js/2.5.3/less.min.js"></script>
                <script type="text/javascript">
                  less.watch();
                </script>
            {% endif %}
        {% endblock less_engine %}
        <title>{% block head_title_base %}{% if SITE_NAME %}{{ SITE_NAME }} | {% endif %}{% block head_title %}
        {% endblock %}{% endblock %}</title>

    </head>
    <body class="{% block body_class %}{% endblock %}" id="{% block body_id %}{% endblock %}">
        <section class="body_wrapper
            {% block wrapper_class %}{% endblock %}">
            {% block header_bar_base %}
                <section id="top_banner"
                         class="topbar
                            {% block navbar_class %}
                            {% endblock %}
                            ">
                    {% block header_bar_images %}
                        <a class="navbar_brand" href="">
                            <img id="header_logo"
                                 src="{% static 'images/assets/Racquet_and_balls.png' %}"/>
                            Company Title
                        </a>
                    {% endblock header_bar_images %}
                    {% block header_bar_nav %}
                        <nav class="pure-menu pure-menu-horizontal nav header" id="header_bar_nav">
                            <a href="{% url 'home' %}">HOME</a>
                            {% if request.user.is_authenticated %}
                                <a href="{{ request.user.profile.get_absolute_url }}">
                                    <i class="icon-briefcase"></i> {% trans "ACCOUNT" %}
                                </a>
                                {% if request.user.is_staff %}
                                    <a href="{% url THEME_ADMIN_URL|default:"admin:index" %}">
                                        <i class="icon-cog">
                                        </i>
                                        {% trans "ADMIN" %}
                                    </a>
                                {% endif %}
                                <a id="account_logout" href="{% url "logout" %}">
                                    <i class="icon-off"></i> {% trans "LOG OUT" %}
                                </a>
                            {% else %}
                                <a href="{% url "login" %}">{% trans "SIGN IN" %}</a>
                            {% endif %}
                        </nav>
                    {% endblock header_bar_nav %}
                </section>
            {% endblock header_bar_base %}

            {% block page_header_base %}
                <section id="page_header"
                         class="">
                    {% block page_header_top %}
                        <h2>Page Header</h2>
                    {% endblock %}
                    {% block page_header_bottom %}
                    {% endblock page_header_bottom %}
                </section>
            {% endblock page_header_base %}

            {% block body_base %}
                <section class="body_container">
                    {% include "_messages.html" %}
                    {% block body %}
                    {% endblock body %}
                </section>
            {% endblock body_base %}

            {% block page_footer %}
                {% include "common/footer.html" %}
            {% endblock page_footer %}

        </section>


        {% block body_script %}
            <!-- base.html: body_script -->
        {% endblock %}

        {% block extra_script %}
            <!-- base.html: body_extra_script -->
        {% endblock %}

        {% block page_script %}
            <!-- base.html: body_page_script -->
        {% endblock %}

        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}

        {% block render_bundles %}
            {# Add logic to render bundles #}
            <!-- Render bundles here -->
        {% endblock %}

        {% block initialize_bundles %}
            {# Add logic to initialize bundles #}
        {% endblock %}

        {% block body_script_final %}
            <!-- base.html: body_script_final -->
        {% endblock %}

    </body>
</html>

tennisblock/webapp/templates/common/footer.html
<!-- common/footer.html -->
<ul class="nav justify-content-center">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'contact' %}">Contact Us</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About Us</a>
    </li>
    <li class="nav-item" id="foot_facebook">
        <a class="nav-link" href="https://www.facebook.com/tennisblock"
           target="_blank"><img
                src="/static/images/facebook/FB-f-Logo__blue_29.png"/></a>
    </li>
    <li class="nav-item" id="foot_twitter">
        <a class="nav-link" href="https://twitter.com/tennisblock"
           target="_blank"><img src="/static/images/twitter-bird-light-bgs.png" height="30" width="30"/>
        </a>
    </li>
</ul>

tennisblock/webapp/templates/common/navbar.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-lg top-navbar" id="navbar">
    <a class="navbar-brand" href="#">
        <img src="{% static 'img/dummy-logo.png' %}"/>
    </a>

    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link text-white"
               href="#" id="toggler"><i class="fa fa-bars fa-2x"></i></a>
        </li>
    </ul>

    <ul class="navbar-nav">
        <li class="nav-item dropdown avatar-dropdown">
            <a class="nav-link dropdown-toggle text-white"
               href="#" id="navbarDropdown" data-toggle="dropdown">
                <img src="{% static 'img/medium-default-avatar.png' %}"
                     width="60"
                     height="60">
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <div class="dropdown-divider"></div>
                <a class="dropdown-item"
                   href="{% url 'logout' %}">Logout
                </a>
            </div>
        </li>
    </ul>
</nav>

tennisblock/webapp/templates/common/sidebar.html
{% load wagtailcore_tags %}

<div class="side-navbar h-100">
    <ul class="top">
        <li class="{% if page and page.slug == 'home' %}active{% endif %}">
            <a href="/home/"><i class="fa fa-home"></i> Home</a>
        </li>

        {% url 'schedule:schedule' as schedule_url %}
        <li class="{% if request.path == schedule_url %}active{% endif %}">
            <a href="{{ schedule_url }}"><i class="fa fa-calendar"></i> Schedule</a>
        </li>

        {% url 'availability:main' as availability_url %}
        <li class="{% if request.path == availability_url %}active{% endif %}">
            <a href="{{ availability_url }}"><i class="fa fa-calendar-o"></i> Availability</a>
        </li>

        {% url 'members:player_list' as players_url %}
        <li class="{% if request.path == players_url %}active{% endif %}">
            <a href="{{ players_url }}"><i class="fa fa-users"></i>Players</a>
        </li>

        {% url 'members:block_react' as block_members_react_url %}
        <li class="{% if request.path == block_members_react_url %}active{% endif %}">
            <a href="{{ block_members_react_url }}">
                <i class="fa fa-sitemap"></i>
                Season Members
            </a>
        </li>

        {% url 'season:seasons' as seasons_url %}
        <li class="{% if request.path == seasons_url %}active{% endif %}">
            <a href="{{ seasons_url }}"><i class="fa fa-cog"></i> Seasons</a>
        </li>

        {% if request.user.is_staff and request.user.is_superuser %}
            <li>
                <a href="{% url 'wagtailadmin_login' %}" target="_blank"><i class="fa fa-cog"></i> CMS Admin</a>
            </li>
            <li>
                <a href="{% url 'admin:index' %}" target="_blank"><i class="fa fa-cog"></i> Django Admin</a>
            </li>
        {% endif %}
    </ul>

    <ul class="bottom">
        <li class="{% if page and page.slug == 'about-us' %}active{% endif %}">
            <a href="/about-us/"><i class="fa fa-info-circle"></i> About Us</a>
        </li>

        {% url 'contact' as contact_url %}
        <li class="{% if request.path == contact_url %}active{% endif %}">
            <a href="{{ contact_url }}"><i class="fa fa-envelope-o"></i> Contact Us</a>
        </li>
    </ul>
</div>