tennisblock/api/urls.py
from django.urls import path, re_path, register_converter

from .availability import AvailabilityView
from .members import SeasonPlayerView, SeasonSubs
from .blocksheet import blockSheet
from .blockschedule import (SubsView, BlockPlayers,
                            MatchData, BlockSchedule,
                            BlockDates, AllPlayers)

from .notify import (ScheduleNotifyView, PlayerVerifyView, PlayerNotifyView)

from .views.season import get_seasons, get_current_season, CouplesView
from .teams import Teams, PickMatch

from . import converters

register_converter(converters.BlockDateConverter, 'date')

app_name = 'api'
urlpatterns = (
    path('seasons/', get_seasons,
         name='seasons'),
    path('currentseason/', get_current_season,
         name='current_season'),
    path('pickteams/<date:date>/', Teams.as_view(),
         name='pickteams_for_date'),
    path('pickteams/', Teams.as_view(),
         name='pickteams'),
    path('pickmatch/<date:date>/<int:setnumber>/', PickMatch.as_view(),
         name='pickmatch_for_date'),
    path('blocksheet/<date:date>/', blockSheet,
         name='blocksheet_for_date'),
    path('blocksheet/', blockSheet,
         name='blocksheet'),
    path('blockdates/', BlockDates.as_view(),
         name='blockdates'),
    path('subs/<date:date>/', SubsView.as_view(),
         name='subs_for_date'),
    path('subs/', SubsView.as_view(),
         name='subs'),
    path('blockplayers/<date:date>/',
         BlockPlayers.as_view(),
         name='blockplayers_for_date'),
    path('blockplayers/', BlockPlayers.as_view(),
         name='blockplayers'),
    path('players/', AllPlayers.as_view(),
         name='all_players'),
    path('scheduleverify/<date:date>/', ScheduleNotifyView.as_view(),
         name='scheduleverify_for_date'
         ),
    path('blockschedule/', BlockSchedule.as_view(),
         name='blockschedule'),
    path('blockschedule/<date:date>/', BlockSchedule.as_view(),
         name='blockschedule_for_date'),
    path('matchdata/<date:date>/', MatchData.as_view(),
         name='matchdata_for_date'),
    path('matchdata/', MatchData.as_view(),
         name='matchdata'),
    path('availability/', AvailabilityView.as_view(),
            name='availability'),
    path('members/<int:id>/', SeasonPlayerView.as_view(),
         name='members_by_date'),
    path('members/', SeasonPlayerView.as_view(),
         name='members'),
    path('member_subs/', SeasonSubs.as_view(),
         name='season_subs'),
    path('couples/', CouplesView.as_view(),
         name='couples'),
    path('couples/<int:season_id>/', CouplesView.as_view(),
         name='couples_for_season'),
    path('notify/<date:date>/', ScheduleNotifyView.as_view(),
         name='notify'),

    path('verifyplayer/<int:player_id>/<date:date>/', PlayerVerifyView.as_view(),
         name='verify_player'),
    path('notifyplayer/<int:player_id>/<date:date>/', PlayerNotifyView.as_view(),
         name='notify_player'),
)

tennisblock/members/urls.py
from django.urls import re_path

from .views import (MembersView, MembersViewAngular, MembersViewReact,
                    PlayerListView, PlayerDetailView,
                    PlayerUpdateView, PlayerDeleteView,
                    PlayerCreateView, SeasonPlayerFormView,
                    SeasonPlayerUpdate)

app_name = 'members'
urlpatterns = [
    re_path(r'^$', MembersViewReact.as_view(), name='block_react'),
    re_path(r'^blockmembers/$', MembersView.as_view(), name='block'),
    re_path(r'^form/$', SeasonPlayerFormView.as_view(), name='members_form'),
    re_path(r'^update/$', SeasonPlayerUpdate.as_view(), name='members_update'),
    re_path(r'^player/list/$', PlayerListView.as_view(), name='player_list'),
    re_path(r"^player/create/$", PlayerCreateView.as_view(), name="player_create"),
    re_path(r'^player/(?P<pk>\d+)/detail/$', PlayerDetailView.as_view(), name='player_detail'),
    re_path(r'^player/(?P<pk>\d+)/update/$', PlayerUpdateView.as_view(), name='player_update'),
    re_path(r'^player/(?P<pk>\d+)/delete/$', PlayerDeleteView.as_view(), name='player_delete'),
    re_path(r'^add/$', PlayerCreateView.as_view(), name='addplayer'),
]

tennisblock/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from views import *

urlpatterns = patterns('',
               # Examples:
               url(r'^$', HomeView.as_view(), name='home'),
               url(r'^schedule/notify/(?P<date>\d{4}-\d{1,2}-\d{1,2})/?',
                   ScheduleNotify.as_view(),name="schedule_notify"),
               url(r'^schedule/', BlockSchedule.as_view(),name='schedule'),
               url(r'^availability/', AvailabilityView.as_view(),
                   name='availability'),

               url(r'^api/', include('tennisblock.api.urls')),
               url(r'^playsheet/', PlaysheetView.as_view()),
               url(r'^members/', include('tennisblock.members.urls')),
               url(r'^contact/?', ContactView.as_view(),name="contact"),
               url(r'^about/?', AboutView.as_view(),name="about"),
               url(r'^accounts/', include('tennisblock.accounts.urls')),
               url(r'^seasons/$', SeasonsView.as_view(),name="seasons"),
               url(r'^seasons/(?P<pk>\d+)/$', SeasonsView.as_view(),name="season_view"),
               url(r'^couples/(?P<pk>\d+)/$', CouplesView.as_view(),name="couple_editor"),

               # Uncomment the next line to enable the admin:
               url(r'^kag3hewb/', include(admin.site.urls)),
       )

tennisblock/members/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from blockdb.models import Player


class UserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]

class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = [
            'gender',
            'ntrp',
            'microntrp',
            'phone'
        ]

tennisblock/members/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render, get_object_or_404
from django.forms.models import modelformset_factory, inlineformset_factory, BaseModelFormSet
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, ListView, DetailView, FormView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import SingleObjectMixin
from django.urls import reverse

from .forms import UserForm, PlayerForm
from blockdb.models import Player, SeasonPlayer
from api.apiutils import get_current_season
from TBLib.view import TennisLoginView
from TBLib.view import class_login_required

from members import signals

@class_login_required
class PlayerListView(ListView):
    template_name = "members/players.html"
    context_object_name = 'players'
    queryset = Player.objects.all().order_by('user__last_name', 'user__first_name')

@class_login_required
class PlayerDetailView(DetailView):
    queryset = Player.objects.all()
    template_name = "members/player_detail.html"
    context_object_name = 'player'

@class_login_required
class PlayerUpdateView(TemplateView):
    template_name = "members/player_form.html"
    success_url = 'members:player_list'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """ Process the results to see if they have been updated.. """

        if kwargs.get('pk', None):
            player = Player.objects.get(pk=kwargs.get('pk'))
            user_form = UserForm(request.POST, instance=player.user)
            player_form = PlayerForm(request.POST, instance=player)
        else:
            # Create Method
            user_form = UserForm(request.POST)
            player_form = PlayerForm(request.POST)

        if user_form.is_valid() and player_form.is_valid():
            return self.form_valid(user_form, player_form)

        if not user_form.is_valid():
            return self.form_invalid(user_form)

        if not player_form.is_valid():
            return self.form_invalid(player_form)

        return self.form_invalid(user_form)

    def get_success_url(self):
        return reverse(self.success_url)

    def form_valid(self, user_form, player_form):
        if user_form.changed_data:
            user = user_form.instance
            user.save()

        if player_form.changed_data:
            player = player_form.instance
            player.save()
            signals.player_updated.send(
                sender=player,
                player=player,
                request=self.request
            )

        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        """If the form is invalid, render the invalid form."""
        return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        player_obj = get_object_or_404(Player, pk=kwargs.get('pk', None))
        user_obj = player_obj.user
        context['player'] = player_obj
        context['user_form'] = UserForm(instance=user_obj)
        context['player_form'] = PlayerForm(instance=player_obj)
        return context

@class_login_required
class PlayerCreateView(TemplateView):
    template_name = "members/player_form.html"
    success_url = 'members:player_list'

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        """ Process the results to see if they have been updated.. """
        user_form = UserForm(request.POST)
        player_form = PlayerForm(request.POST)

        if user_form.is_valid() and player_form.is_valid():
            return self.form_valid(user_form, player_form)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['user_form'] = UserForm()
        context['player_form'] = PlayerForm()
        return context

    def form_valid(self, user_form, player_form):
        user_obj = user_form.save()
        player_obj = player_form.save(commit=False)
        player_obj.user = user_obj
        player_obj.save()
        signals.player_created.send(
            sender=player_obj,
            player=player_obj,
            request=self.request
        )
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse(self.success_url)


@class_login_required
class PlayerDeleteView(DeleteView):
    model = Player
    template_name = "members/player_confirm_delete.html"

    def form_valid(self, form):
        response = super().form_valid(form)
        signals.player_deleted.send(
            sender=self.object,
            player=self.object,
            request=self.request
        )
        return response

    def delete(self, request, *args, **kwargs):
        """ Need to delete the user, not the player """
        player = self.get_object()
        success_url = self.get_success_url()
        uid = player.user.pk
        pid = player.id
        player.user.delete()
        print(f"Delete player {pid} and user {uid}")
        return HttpResponseRedirect(success_url)

    def get_success_url(self):
        return reverse("members:player_list")


@class_login_required
class PlayersView(TennisLoginView):
    template_name = "players.html"

    def get_players(self):
        s = get_current_season()
        sp = Player.objects.all().order_by('last_name', 'first_name')
        return sp

    def get_queryset(self):
        queryset = super().get_queryset()

        q = self.request.GET.get("q")
        if q:
            return queryset.filter(first__icontains=q)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['players'] = self.get_players()
        return context


@class_login_required
class MembersViewAngular(TennisLoginView):
    template_name = "members/members_view_angular.html"
    members_only = False

    def get_players(self):
        s = get_current_season()
        sp = SeasonPlayer.objects.filter(season=s)
        return [p.player for p in sp if (not self.members_only or p.blockmember)]

    def get_queryset(self):
        queryset = super().get_queryset()

        q = self.request.GET.get("q")
        if q:
            return queryset.filter(first__icontains=q)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['players'] = self.get_players()
        return context


@class_login_required
class MembersView(TennisLoginView):
    template_name = "members/members_view.html"
    members_only = False

    def get_players(self):
        s = get_current_season()
        sp = SeasonPlayer.objects.filter(season=s).select_related('player')
        if self.members_only:
            sp.filter(blockmember=True)
        sp.order_by('player__user__last_name', 'player__gender')
        # sp.values('id',
        #           'player__user__first_name', 'player__user__last_name',
        #           'player__gender', 'player__ntrp', 'player__microntrp',
        #           'player__user__email', 'player__phone', 'blockmember')
        return sp

    def get_queryset(self):
        queryset = super().get_queryset()

        q = self.request.GET.get("q")
        if q:
            return queryset.filter(first__icontains=q)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['players'] = self.get_players()
        return context


@class_login_required
class MembersViewReact(TennisLoginView):
    template_name = "members/members_view_react.html"

    def get_players(self):
        s = get_current_season()
        sp = SeasonPlayer.objects.filter(season=s).select_related('player')
        sp.order_by('player__user__last_name', 'player__gender')
        return sp

    def get_queryset(self):
        queryset = super().get_queryset()

        q = self.request.GET.get("q")
        if q:
            return queryset.filter(first__icontains=q)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['players'] = self.get_players()
        return context


@class_login_required
class SeasonPlayerView(MembersView):
    members_only = True


class SeasonPlayerFormSet(BaseModelFormSet):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        s = get_current_season()
        self.queryset = Player.objects.all()


@class_login_required
class SeasonPlayerFormView(MembersView):
    template_name = "members_form.html"
    members_only = True

    def _get_inline_formset(self, data=None):
        """ Get an inline formset
        """

        AvailFormSet = modelformset_factory(Player)
        # s = get_current_season()
        queryset = Player.objects.all()
        return AvailFormSet(queryset=queryset)

    def _get_formset(self, data=None):
        """ Create the formset object """
        fs = modelformset_factory(Player, formset=SeasonPlayerFormSet)
        return fs

    def get(self, request, **kwargs):
        context = self.get_context_data(**kwargs)
        PlayerFormSet = self._get_formset()
        fs = PlayerFormSet()
        context['formset'] = fs

        return render(request,
                      self.template_name,
                      context
                      )

    def post(self, request):
        context = self.get_context_data()
        PlayerFormSet = self._get_formset()
        fs = PlayerFormSet(request.POST)

        if fs.is_valid():
            print("Valid Formset!")

            return render(request,
                          self.thankyou_template,

tennisblock/members/templates/members/add.html
{% extends "common/base.html" %}
{% load static %}

{% block page_style %}
    {{ block.super }}
    <!-- about.html: page_style -->

    <link rel="stylesheet/less" type="text/less" href="{% static 'less/schedule.less' %}">
{% endblock %}

{% block angular_script %}
    {{ block.super }}

    <script src="{% static 'js/angular/controllers/Home.js' %}" type="text/javascript"></script>

{% endblock %}

{% block title %}
add
{% endblock %}

{% block body %}
    <div id="container" class="home dynamic">
        <div id="content" class="dynamic">

            {% verbatim %}
            <div id="textContent">
                <div id="blockheading" class="dynamic">
                    <h2>About Us</h2>
                </div>
            </div>
            {% endverbatim %}

        </div>
    </div>


{% endblock %}

tennisblock/members/templates/members/members_view.html
{% extends "common/angular_base.html" %}
{% load static %}

{% block page_style %}
    {{ block.super }}
    <!-- about.html: page_style -->

{% endblock %}

{% block body_script %}
    {{ block.super }}
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.js"></script>
{% endblock %}

{% block style_base %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.css"/>
{% endblock %}


{% block page_content %}
    
    <div id="content" class="dynamic">
        <h3>Block Members</h3>
        <table id="player_table" class="display table
                table-responsive table-fixed
                table-striped table-bordered table-hover" style="width:100%;">
            <thead class="thead-dark sticky-top">
            <tr>
                <th class="col-2">Name</th>
                <th class="">Gender</th>
                <th class="">NTRP</th>
                <th class="">uNTRP</th>
                <th class="">Email</th>
                <th class="">Phone</th>
                <th class="">Block Member?</th>
                <th class="">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for sp in players %}
                {% with sp.player as player %}
                    <tr>
                        <td class="">{{ player.full_name }}</td>
                        <td class="">{{ player.gender }}</td>
                        <td class="">{{ player.ntrp }}</td>
                        <td class="">{{ player.untrp }}</td>
                        <td class="">{{ player.email }}</td>
                        <td class="">{{ player.phone }}</td>
                        <td class="">
                            <input
                                    type="checkbox"
                                    name="bp"
                                    value="{{ sp.id }}"
                                    {% if sp.blockmember %}
                                    checked
                                    {% endif %}
                            >
                        </td>
                        {% if not sp.blockmember %}
                            <td class="">
                                <button class="delete-member btn btn-danger"
                                        data-id="{{ sp.id }}">
                                    Delete
                                </button>
                            </td>
                        {% endif %}
                    </tr>
                {% endwith %}
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock page_content %}

{% block tennisblock_script %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/members.js' %}"></script>
{% endblock %}

tennisblock/members/templates/members/members_view_angular.html
{% extends "common/angular_base.html" %}
{% load static %}

{% block page_style %}
    {{ block.super }}
    <!-- about.html: page_style -->

{% endblock %}

{% block angular_script %}
    {{ block.super }}

    <script src="{% static 'js/angular/controllers/members-controller.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/angular/directives/block-members.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/angular/directives/block-member.js' %}" type="text/javascript"></script>

{% endblock %}

{% block page_content %}
    <div id="content" class="dynamic">

        {% verbatim %}
        <block-members id="members" >
        </block-members>
        {% endverbatim %}

    </div>

{% endblock %}

tennisblock/members/templates/members/members_view_react.html
{% extends "common/angular_base.html" %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block page_style %}
    {{ block.super }}
    <!-- about.html: page_style -->

{% endblock %}

{% block body_script %}
    {{ block.super }}
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.js"></script>
{% endblock %}

{% block style_base %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/datatables.min.css"/>
{% endblock %}


{% block page_content %}
    
    <div class="dynamic" id="content">
        <h3>Block Members React</h3>
    </div>

{% endblock page_content %}

{% block render_css_bundles %}
    {% render_bundle 'style_base' 'css' 'ASSETS' %}
    {% render_bundle 'blockmembers_page' 'css' 'ASSETS' %}
{% endblock %}

{% block render_bundles %}
    {{ block.super }}
    {% if render_bundles %}
        <!-- Render bundles here -->
        {% render_bundle 'vendor' 'js' %}
        {% render_bundle 'Members' 'js' %}
    {% endif %}
{% endblock %}

{% block initialize_bundles %}
    {{ block.super }}
    {% if render_bundles %}
        {% include "bundles/common_options.html" %}
        <!-- Initialize bundles -->
        <script type="text/javascript">
          console.log('Initialize component')
          Members(
            Object.assign(
              tennisblock_page_elements,
              {members_el: 'content'}
            ),
            Object.assign(
              tennisblock_page_options,
              {
                members_opts: {
                  apis: {
                    blockmembers: '{% url "api:members" %}',
                    allplayers: '{% url "api:all_players" %}',
                    season_subs: '{% url "api:season_subs" %}',
                  }
                },
              }
            )
          )

        </script>
    {% endif %}
{% endblock %}

tennisblock/members/templates/members/player_confirm_delete.html
{% extends "site_base.html" %}
{% load static %}
{% load i18n %}

{% block page_style %}
    {{ block.super }}
    <!-- about.html: page_style -->
    <link rel="stylesheet" href="{% static 'css/members.css' %}">

{% endblock %}

{% block page_content %}
    <div id="content" class="dynamic">
        <h3>Delete player {{player.first}} {{player.last}}?</h3>
        <form method="post">
            {% csrf_token %}
            <button ><a href="{% url 'members:player_list' %}">Cancel</a></button>
            <button type="submit">Delete Player</button>
        </form>
    </div>

{% endblock %}

tennisblock/members/templates/members/player_detail.html
{% extends "common/site_base.html" %}
{% load static %}
{% load i18n %}

{% block page_style %}
    {{ block.super }}
    <!-- about.html: page_style -->

{% endblock %}

{% block page_content %}
    <div id="content" class="dynamic">

        <table class="pure-table">
            <thead>
                <tr>
                    <th>First</th>
                    <th>Last</th>
                    <th>Gender</th>
                    <th>NTRP</th>
                    <th>uNTRP</th>
                    <th>email</th>
                    <th>phone</th>
                    <th>Blockmember</th>
                    <th>SeasonPlayer</th>
                </tr>
            </thead>
                <tr>
                    <th>{{player.first}}</th>
                    <th>{{player.last}}</th>
                    <th>{{player.gender}}</th>
                    <th>{{player.ntrp}}</th>
                    <th>{{player.microntrp}}</th>
                    <th>{{player.email}}</th>
                    <th>{{player.phone}}</th>
                    <th>BlockMember</th>
                    <th>SeasonPlayer</th>
                </tr>
        </table>

    </div>

{% endblock %}

tennisblock/members/templates/members/player_form.html
{% extends "site_base.html" %}
{% load static %}
{% load i18n %}
{% load bootstrap %}

{% block page_style %}
    {{ block.super }}
    <!-- about.html: page_style -->

{% endblock %}

{% block page_content %}
    <div id="content" class="dynamic">

        <h1>{% if player %}{% trans "Edit Player" %}{% else %}{% trans "Create Player" %}{% endif %}</h1>
        {% if player_form %}
            {% url "members:player_update" pk=player.pk as post_url %}
        {% else %}
            {% url "members:player_create" as post_url %}
        {% endif %}

        <form action="{{ post_url }}" method="POST" class="form form-horizontal">
            {% csrf_token %}
            {{ user_form|bootstrap }}
            {{ player_form|bootstrap }}
            <div class="form-actions">
                <a href="{% url 'members:player_list' %}" class="btn">{% trans "Cancel" %}</a>
                {% if player %}
                    <a href="{% url 'members:player_delete' pk=player.pk %}"
                       class="btn btn-danger">
                        {% trans "Delete" %}
                    </a>
                {% endif %}
                <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
            </div>
        </form>

    </div>

{% endblock %}

tennisblock/members/templates/members/players.html
{% extends "site_base.html" %}
{% load static %}
{% load i18n %}

{% block page_style %}
    {{ block.super }}
    <!-- about.html: page_style -->

{% endblock %}

{% block page_content %}
    <div id="content" class="dynamic">

        <a href="{% url "members:player_create" %}" class="btn btn-mini">
            <i class="icon icon-pencil"></i>
            {% trans "Create Player" %}
        </a>
        <table class="pure-table pure-table-bordered pure-table-striped">
            <thead>
                <tr>
                    <th>First</th>
                    <th>Last</th>
                    <th>Gender</th>
                    <th>NTRP</th>
                    <th>uNTRP</th>
                    <th>email</th>
                    <th>phone</th>
                    <th>Modify</th>
                </tr>
            </thead>
            {% for player in players %}
                <tr>
                    <td>{{player.first}}</td>
                    <td>{{player.last}}</td>
                    <td>{{player.gender}}</td>
                    <td>{{player.ntrp}}</td>
                    <td>{{player.microntrp}}</td>
                    <td>{{player.email}}</td>
                    <td>{{player.phone}}</td>
                    <td>
                        <a href="{% url 'members:player_update' pk=player.pk %}"
                           class="pure-button pure-button-primary">
                            <i class="icon icon-pencil"></i>
                            {% trans "Edit" %}
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>

    </div>

{% endblock %}