tennisblock/api/urls.py
from django.urls import path, re_path, register_converter

from .availability import AvailabilityView
from .members import SeasonPlayerView, SeasonSubs
from .blocksheet import blockSheet
from .blockschedule import (SubsView, BlockPlayers,
                            MatchData, BlockSchedule,
                            BlockDates, AllPlayers)

from .notify import (ScheduleNotifyView, PlayerVerifyView, PlayerNotifyView)

from .views.season import get_seasons, get_current_season, CouplesView
from .teams import Teams, PickMatch

from . import converters

register_converter(converters.BlockDateConverter, 'date')

app_name = 'api'
urlpatterns = (
    path('seasons/', get_seasons,
         name='seasons'),
    path('currentseason/', get_current_season,
         name='current_season'),
    path('pickteams/<date:date>/', Teams.as_view(),
         name='pickteams_for_date'),
    path('pickteams/', Teams.as_view(),
         name='pickteams'),
    path('pickmatch/<date:date>/<int:setnumber>/', PickMatch.as_view(),
         name='pickmatch_for_date'),
    path('blocksheet/<date:date>/', blockSheet,
         name='blocksheet_for_date'),
    path('blocksheet/', blockSheet,
         name='blocksheet'),
    path('blockdates/', BlockDates.as_view(),
         name='blockdates'),
    path('subs/<date:date>/', SubsView.as_view(),
         name='subs_for_date'),
    path('subs/', SubsView.as_view(),
         name='subs'),
    path('blockplayers/<date:date>/',
         BlockPlayers.as_view(),
         name='blockplayers_for_date'),
    path('blockplayers/', BlockPlayers.as_view(),
         name='blockplayers'),
    path('players/', AllPlayers.as_view(),
         name='all_players'),
    path('scheduleverify/<date:date>/', ScheduleNotifyView.as_view(),
         name='scheduleverify_for_date'
         ),
    path('blockschedule/', BlockSchedule.as_view(),
         name='blockschedule'),
    path('blockschedule/<date:date>/', BlockSchedule.as_view(),
         name='blockschedule_for_date'),
    path('matchdata/<date:date>/', MatchData.as_view(),
         name='matchdata_for_date'),
    path('matchdata/', MatchData.as_view(),
         name='matchdata'),
    path('availability/', AvailabilityView.as_view(),
            name='availability'),
    path('members/<int:id>/', SeasonPlayerView.as_view(),
         name='members_by_date'),
    path('members/', SeasonPlayerView.as_view(),
         name='members'),
    path('member_subs/', SeasonSubs.as_view(),
         name='season_subs'),
    path('couples/', CouplesView.as_view(),
         name='couples'),
    path('couples/<int:season_id>/', CouplesView.as_view(),
         name='couples_for_season'),
    path('notify/<date:date>/', ScheduleNotifyView.as_view(),
         name='notify'),

    path('verifyplayer/<int:player_id>/<date:date>/', PlayerVerifyView.as_view(),
         name='verify_player'),
    path('notifyplayer/<int:player_id>/<date:date>/', PlayerNotifyView.as_view(),
         name='notify_player'),
)

tennisblock/schedule/urls.py
from django.urls import re_path, path

from .views import (
    BlockSchedule,
)

app_name = 'schedule'
urlpatterns = (
    re_path(r'(?P<date>\d{4}-\d{1,2}-\d{1,2})?',
            BlockSchedule.as_view(), name='schedule'),
    re_path(r'^(?P<pk>\d+)/$',
            BlockSchedule.as_view(), name='season_schedule'),
)

tennisblock/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from views import *

urlpatterns = patterns('',
               # Examples:
               url(r'^$', HomeView.as_view(), name='home'),
               url(r'^schedule/notify/(?P<date>\d{4}-\d{1,2}-\d{1,2})/?',
                   ScheduleNotify.as_view(),name="schedule_notify"),
               url(r'^schedule/', BlockSchedule.as_view(),name='schedule'),
               url(r'^availability/', AvailabilityView.as_view(),
                   name='availability'),

               url(r'^api/', include('tennisblock.api.urls')),
               url(r'^playsheet/', PlaysheetView.as_view()),
               url(r'^members/', include('tennisblock.members.urls')),
               url(r'^contact/?', ContactView.as_view(),name="contact"),
               url(r'^about/?', AboutView.as_view(),name="about"),
               url(r'^accounts/', include('tennisblock.accounts.urls')),
               url(r'^seasons/$', SeasonsView.as_view(),name="seasons"),
               url(r'^seasons/(?P<pk>\d+)/$', SeasonsView.as_view(),name="season_view"),
               url(r'^couples/(?P<pk>\d+)/$', CouplesView.as_view(),name="couple_editor"),

               # Uncomment the next line to enable the admin:
               url(r'^kag3hewb/', include(admin.site.urls)),
       )

tennisblock/schedule/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class NotifyForm(forms.Form):
    message = forms.CharField(max_length=500,
                              required=True,
                              label=_('Enter your message'),
                              widget=forms.Textarea({
                                  'id':'bootstrap-message',
                                  'cols': '60', 'rows': '10'})
    )

tennisblock/schedule/views.py
from django.views.generic import TemplateView
from TBLib.season import SeasonManager
from TBLib.view import class_login_required

from .serializers import MeetingSerializer


@class_login_required
class BlockSchedule(TemplateView):
    """
    display the block schedule for the current, or specified block.

    If the block pk is not specified, use the 'current block'
    """
    template_name = "schedule/index.html"

    def get(self, request, pk=None, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        sm = SeasonManager()
        meetings = sm.get_meeting_list()
        serialized = MeetingSerializer(meetings, many=True)
        context['meetings'] = serialized.data
        return context

tennisblock/schedule/templates/schedule/index.html
{% extends "common/angular_base.html" %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block title %}
    schedule
{% endblock %}

{% block page_content %}

    <div id="react-schedule"></div>

    <div class="row">
        <div class="col" id="schedule"></div>
    </div>

    <div class="row">
        <div class="col" id="match_review"></div>
    </div>


    <div class="row">
        <div id="dialog_confirm"></div>
    </div>

{% endblock page_content %}

{% block render_css_bundles %}
    {% render_bundle 'style_base' 'css' 'ASSETS' %}
    {% render_bundle 'schedule' 'css' 'ASSETS' %}
{% endblock %}

{% block render_bundles %}
    {{ block.super }}
    {% if render_bundles %}
        <!-- Render bundles here -->
        {% render_bundle 'vendor' 'js' %}
        {% render_bundle 'Schedule' 'js' %}
    {% endif %}
{% endblock %}

{% block initialize_bundles %}
    {{ block.super }}
    {% if render_bundles %}
        {% include "bundles/common_options.html" %}
        <!-- Initialize bundles -->
        <script type="text/javascript">
          console.log('Initialize component')
          Schedule(
            Object.assign(
              tennisblock_page_elements,
              {schedule_el: 'react-schedule'}
            ),
            Object.assign(
              tennisblock_page_options,
              {
                schedule_opts: {
                  apis: {
                    blockdates: '{% url "api:blockdates" %}',
                    matchdata: '{% url "api:matchdata_for_date" "0000-00-00" %}',
                    blockplayers: '{% url "api:blockplayers_for_date" "0000-00-00" %}',
                    subs: '{% url "api:subs_for_date" "0000-00-00" %}',
                    blockschedule: '{% url "api:blockschedule_for_date" "0000-00-00" %}',
                    notify: '{%  url "api:notify" "0000-00-00" %}',
                    verifystatus: '{% url "api:scheduleverify_for_date" "0000-00-00" %}',
                    notify_player: '{% url "api:notify_player" "000" "0000-00-00" %}',
                    verify_player: '{% url "api:verify_player" "000" "0000-00-00" %}',
                  }
                },
                teams_opts: {
                  apis: {
                    matchdata: '{% url "api:matchdata_for_date" "0000-00-00" %}',
                    pickteams: '{% url "api:pickteams_for_date" "0000-00-00" %}',
                    recalculate_match: '{% url "api:pickmatch_for_date" "0000-00-00" "0" %}'
                  }
                },
                availability_opts: {
                  apis: {
                    availability_url: '{% url "api:availability" %}',
                    blockdates: '{% url 'api:blockdates' %}',
                  }
                }
              }
            )
          )

        </script>
    {% endif %}
{% endblock %}