tennisblock/api/urls.py
from django.urls import path, re_path, register_converter

from .availability import AvailabilityView
from .members import SeasonPlayerView, SeasonSubs
from .blocksheet import blockSheet
from .blockschedule import (SubsView, BlockPlayers,
                            MatchData, BlockSchedule,
                            BlockDates, AllPlayers)

from .notify import (ScheduleNotifyView, PlayerVerifyView, PlayerNotifyView)

from .views.season import get_seasons, get_current_season, CouplesView
from .teams import Teams, PickMatch

from . import converters

register_converter(converters.BlockDateConverter, 'date')

app_name = 'api'
urlpatterns = (
    path('seasons/', get_seasons,
         name='seasons'),
    path('currentseason/', get_current_season,
         name='current_season'),
    path('pickteams/<date:date>/', Teams.as_view(),
         name='pickteams_for_date'),
    path('pickteams/', Teams.as_view(),
         name='pickteams'),
    path('pickmatch/<date:date>/<int:setnumber>/', PickMatch.as_view(),
         name='pickmatch_for_date'),
    path('blocksheet/<date:date>/', blockSheet,
         name='blocksheet_for_date'),
    path('blocksheet/', blockSheet,
         name='blocksheet'),
    path('blockdates/', BlockDates.as_view(),
         name='blockdates'),
    path('subs/<date:date>/', SubsView.as_view(),
         name='subs_for_date'),
    path('subs/', SubsView.as_view(),
         name='subs'),
    path('blockplayers/<date:date>/',
         BlockPlayers.as_view(),
         name='blockplayers_for_date'),
    path('blockplayers/', BlockPlayers.as_view(),
         name='blockplayers'),
    path('players/', AllPlayers.as_view(),
         name='all_players'),
    path('scheduleverify/<date:date>/', ScheduleNotifyView.as_view(),
         name='scheduleverify_for_date'
         ),
    path('blockschedule/', BlockSchedule.as_view(),
         name='blockschedule'),
    path('blockschedule/<date:date>/', BlockSchedule.as_view(),
         name='blockschedule_for_date'),
    path('matchdata/<date:date>/', MatchData.as_view(),
         name='matchdata_for_date'),
    path('matchdata/', MatchData.as_view(),
         name='matchdata'),
    path('availability/', AvailabilityView.as_view(),
            name='availability'),
    path('members/<int:id>/', SeasonPlayerView.as_view(),
         name='members_by_date'),
    path('members/', SeasonPlayerView.as_view(),
         name='members'),
    path('member_subs/', SeasonSubs.as_view(),
         name='season_subs'),
    path('couples/', CouplesView.as_view(),
         name='couples'),
    path('couples/<int:season_id>/', CouplesView.as_view(),
         name='couples_for_season'),
    path('notify/<date:date>/', ScheduleNotifyView.as_view(),
         name='notify'),

    path('verifyplayer/<int:player_id>/<date:date>/', PlayerVerifyView.as_view(),
         name='verify_player'),
    path('notifyplayer/<int:player_id>/<date:date>/', PlayerNotifyView.as_view(),
         name='notify_player'),
)

tennisblock/season/urls.py
from django.urls import re_path, path

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

from .views import (
    SeasonsView,
    SeasonDetailView,
    SeasonCreate,
    CouplesView
)

app_name = 'season'
urlpatterns = [
    re_path(r'^$', SeasonsView.as_view(), name="seasons"),
    re_path(r'^(?P<pk>\d+)/$',
            SeasonDetailView.as_view(), name="season_detail"),
    re_path(r'^create/',
            SeasonCreate.as_view(), name='create_season'),
    path('<int:pk>/couples/',
         CouplesView.as_view(), name="couple_editor")
]

tennisblock/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from views import *

urlpatterns = patterns('',
               # Examples:
               url(r'^$', HomeView.as_view(), name='home'),
               url(r'^schedule/notify/(?P<date>\d{4}-\d{1,2}-\d{1,2})/?',
                   ScheduleNotify.as_view(),name="schedule_notify"),
               url(r'^schedule/', BlockSchedule.as_view(),name='schedule'),
               url(r'^availability/', AvailabilityView.as_view(),
                   name='availability'),

               url(r'^api/', include('tennisblock.api.urls')),
               url(r'^playsheet/', PlaysheetView.as_view()),
               url(r'^members/', include('tennisblock.members.urls')),
               url(r'^contact/?', ContactView.as_view(),name="contact"),
               url(r'^about/?', AboutView.as_view(),name="about"),
               url(r'^accounts/', include('tennisblock.accounts.urls')),
               url(r'^seasons/$', SeasonsView.as_view(),name="seasons"),
               url(r'^seasons/(?P<pk>\d+)/$', SeasonsView.as_view(),name="season_view"),
               url(r'^couples/(?P<pk>\d+)/$', CouplesView.as_view(),name="couple_editor"),

               # Uncomment the next line to enable the admin:
               url(r'^kag3hewb/', include(admin.site.urls)),
       )

tennisblock/season/forms.py
from django.forms import ModelForm
from django.core.exceptions import ObjectDoesNotExist

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from bootstrap_datepicker_plus import DatePickerInput, TimePickerInput
from blockdb.models import Season, Couple, SeasonPlayer


class SeasonForm(ModelForm):
    class Meta:
        model = Season
        fields = ('name', 'courts', 'firstcourt',
                  'startdate', 'enddate',
                  'blockstart', 'lastdate', 'blocktime')
        widgets = {
            'startdate': DatePickerInput(format='%m/%d/%Y'),
            'enddate': DatePickerInput(format='%m/%d/%Y'),
            'blockstart': DatePickerInput(format='%m/%d/%Y'),
            'lastdate': DatePickerInput(format='%m/%d/%Y'),
            'blocktime': TimePickerInput()
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-inline'
        self.helper.form_method = 'post'


class CoupleForm(ModelForm):

    def __init__(self, season, *args, **kwargs):
        super(CoupleForm, self).__init__(*args, **kwargs)
        allPlayers = SeasonPlayer.objects.filter(season=season)
        couples = Couple.objects.filter(season=season)
        self.fields['male'].queryset = \
            allPlayers.filter(player__gender='M')\
            .exclude(player__id__in=couples.values('male'))
        self.fields['female'].queryset = allPlayers.filter(player__gender='F') \
            .exclude(player__id__in=couples.values('female'))

    def is_valid(self):
        if self.data['name'] == "":
            return False

        try:
            self.spguy = SeasonPlayer.objects.get(pk=self.data['male'])
            self.spgal = SeasonPlayer.objects.get(pk=self.data['female'])
        except ObjectDoesNotExist:
            return False

        return True

    class Meta:
        model = Couple
        fields = ['name', 'male', 'female', 'fulltime',
                  'blockcouple', 'canschedule']

tennisblock/api/views/season.py
from blockdb.models import Season, SeasonPlayer, Couple, Player

from django.db.models import Q
from django.shortcuts import get_object_or_404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from ..apiutils import JSONResponse, get_current_season as gcs, SeasonSerializer


def get_seasons(request):
    """
    List all code snippets, or create a new snippet.
    """
    if request.method == 'GET':
        seasons = Season.objects.all()
        serializer = SeasonSerializer(seasons, many=True)
        return JSONResponse(serializer.data)


def get_current_season(request):
    """
    List all code snippets, or create a new snippet.
    """
    if request.method == 'GET':
        cs = gcs()
        if cs:
            serializer = SeasonSerializer(cs, many=False)
            return JSONResponse(serializer.data)
        else:
            return "Failed"


class CouplesView(APIView):

    permission_classes = [permissions.IsAdminUser]

    def get(self, request, format=None, season_id=None):

        currseason = get_object_or_404(Season, pk=season_id) if season_id else gcs()

        context = {}
        players = SeasonPlayer.objects.filter(season=currseason).all()
        couples = Couple.objects.filter(season=currseason).all()

        player_data = {'guys': [], 'girls': []}
        guys = player_data['guys']
        girls = player_data['girls']

        for sp in players:
            p = sp.player
            data = {
                'id': p.id,
                'spid': sp.id,
                'first': p.user.first_name,
                'last': p.user.last_name,
                'gender': p.gender
            }
            if p.gender == 'F':
                girls.append(data)
            else:
                guys.append(data)

        couple_data = []
        for c in couples:
            data = {
                'id': c.id,
                'name': c.name,
                'guy': c.male.id,
                'girl': c.female.id,
                'fulltime': c.fulltime,
                'as_singles': c.as_singles,
                'blockcouple': c.blockcouple,
            }
            couple_data.append(data)

        context['players'] = player_data
        context['couples'] = couple_data
        context['initial'] = {
            'season': currseason.id,
            'fulltime': False,
            'blockcouple': True,
            'canschedule': True
        }

        return Response(context)

    def post(self, request):
        """
        Update the couples. Expected input:

            couples -- array
            couple: {
              name: 'Name for this couple, i.e. Hendersons',
              guy: <player id of the guy>,
              girl: <player id of the girl>,
              fulltime: <boolean if they are fulltime>,
              as_singles: <boolean if they are coupled as singles>,
          }

        """
        currseason = gcs()
        couples = request.data.get('couples', [])

        result = {
            'status': 'success',
            'updated': [],
            'created': [],
        }

        current_id_list =[]

        for index, couple in enumerate(couples):
            id = couple.get('id')
            name = couple.get('name', '')
            guy = couple.get('guy')
            girl = couple.get('girl')
            fulltime = couple.get('fulltime')
            as_singles = couple.get('as_singles')

            male = Player.objects.get(id=guy)
            female = Player.objects.get(id=girl)

            try:
                if id is not None:
                    c = Couple.objects.get(pk=id)
                else:
                    c = Couple.objects.get(season=currseason, male=male, female=female)
                c.as_singles = as_singles
                c.fulltime = fulltime
                c.name = name
                c.save()

                result['updated'].append({
                    'id': c.id,
                    'index': index,
                })
                current_id_list.append(c.id)

            except Couple.DoesNotExist:
                c = Couple(
                    season=currseason,
                    name=name,
                    male=male,
                    female=female,
                    fulltime=fulltime,
                    as_singles=as_singles,
                    canschedule=True,
                    blockcouple=True
                   )
                c.save()
                current_id_list.append(c.id)

                result['created'].append({
                    'id': c.id,
                    'index': index,
                    'name': c.name,
                })

        # Now, remove extra couples!
        Couple.objects.filter(~Q(id__in=current_id_list)).delete()

        return Response(result)

tennisblock/season/templates/season/couple_editor.html
{% extends "common/angular_base.html" %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block page_content %}

    <div id="root">
    </div>

{% endblock %}

{% block render_css_bundles %}
    {% render_bundle 'style_base' 'css' 'ASSETS' %}
{% endblock %}

{% block render_bundles %}
    {{ block.super }}
    {% if render_bundles %}
        <!-- Render bundles here -->
        {% render_bundle 'vendor' 'js' %}
        {% render_bundle 'CouplesEditor' 'js' %}
    {% endif %}
{% endblock %}

{% block initialize_bundles %}
    {{ block.super }}
    {% if render_bundles %}
        {% include "bundles/common_options.html" %}
        <!-- Initialize bundles -->
        <script type="text/javascript">
          console.log('Initialize component')
          CouplesEditor(
            Object.assign(
              tennisblock_page_elements,
              {editor_el: 'root'}
            ),
            Object.assign(
              tennisblock_page_options,
              {
                season_opts: {
                  couples_url: '{% url "api:couples" %}',
                  initial_state: {}
                }
              }
            )
          )

        </script>
    {% endif %}
{% endblock %}

tennisblock/season/templates/season/season_create.html
{% extends "site_base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block page_content %}
    <div id="blockheading" class="dynamic">
        <h2>Create Season</h2>

        <form
                action="{% url 'season:create_season' %}" %}
                method="post">
            {% csrf_token %}
            {% crispy form %}
        </form>
    </div>
{% endblock %}

{% block body_script %}
    {{ block.super }}
    {{ form.media }}
{% endblock body_script %}

tennisblock/season/templates/season/season_detail.html
{% extends "site_base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block angular_script %}
{% endblock %}

{% block page_content %}
    <div>
        <form
                action="{% url 'season:season_detail' pk=season.pk %}" %}
                method="post">
            {% csrf_token %}
            {% crispy season_form season_form.helper %}
        </form>

        <form action="{% url 'season:season_detail' pk=season.pk %}" method="post">
            {% csrf_token %}
            {% for mtg in meetings %}
                <div class="pure-control-group">
                    <label for="mtg_{{ forloop.counter0 }}">{{ mtg.date }}</label>
                    <input id="mtg_{{ forloop.counter0 }}" name="meetings" type="checkbox"
                           value="{{ forloop.counter0 }}"
                            {% if mtg.holdout %}
                           checked
                            {% endif %}
                    >
                </div>
            {% endfor %}
            <input class="btn btn-primary"
                   type="submit"
                   name="update_holdouts" value="Update Holdouts"/>
        </form>

        <div class="row">
            <div class="col">

                <form
                        action="{% url 'season:season_detail' pk=season.pk %}"
                        method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col">
                            Total of {{ active.count }} Players
                            <ul>
                                {% for player in active %}
                                    <li>
                                        <span>{{ player.name }}</span>
                                        <span>{{ player.ntrp }}</span>
                                        <label for="mtg_{{ forloop.counter0 }}">
                                            {{ mtg.date }}
                                        </label>
                                        <input id="mtg_{{ forloop.counter0 }}"
                                               name="members"
                                               type="checkbox"
                                               value="{{ player.pk }}"
                                                {% if player.active %}
                                               checked="checked"
                                                {% endif %}
                                        >
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="col">
                            <ul>
                                {% for player in inactive %}
                                    <li>
                                        <span>{{ player.name }}</span>
                                        <span>{{ player.ntrp }}</span>
                                        <label for="mtg_{{ forloop.counter0 }}">
                                            {{ mtg.date }}
                                        </label>
                                        <input id="mtg_{{ forloop.counter0 }}"
                                               name="members"
                                               type="checkbox"
                                               value="{{ player.pk }}"
                                                {% if player.active %}
                                               checked="checked"
                                                {% endif %}
                                        >
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <input class="btn btn-primary"
                               type="submit"
                               name="season_players" value="Update Players"/>

                    </div>


                </form>

            </div>


        </div>


    </div>
{% endblock %}

{% block body_script %}
    {{ block.super }}
    {{ form.media }}
{% endblock body_script %}

tennisblock/season/templates/season/seasons.html
{% extends "site_base.html" %}
{% load static %}

{% block page_content %}
    <div id="blockheading" class="dynamic">
        <h2>Block Seasons</h2>
    </div>
    <div>
        <table border="1">
            <thead>
                <tr>
                    <td>Name</td>
                    <td>Courts</td>
                    <td>First Court</td>
                    <td>Start</td>
                    <td>End</td>
                    <td>Block Start</td>
                    <td>Time</td>
                </tr>
            </thead>
            <tbody>
                {% for season in seasons %}
                    <tr>
                        <td><a href="{% url 'season:season_detail' season.pk %}">{{ season.name }}</a></td>
                        <td>{{ season.courts}}</td>
                        <td>{{ season.firstcourt }}</td>
                        <td>{{ season.startdate }}</td>
                        <td>{{ season.enddate }}</td>
                        <td>{{ season.blockstart }}</td>
                        <td>{{ season.blocktime }}</td>
                        <td><a href="{% url 'season:couple_editor' season.pk %}">Couple Editor</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div>
        {% if season %}
            <h3>Current Season:{{ season.name }}</h3>
            <table border="1">
                <thead>
                    <tr>
                        <td>Date</td>
                        <td>Holdout</td>
                    </tr>
                </thead>
                <tbody>
                    {% for mtg in meetings %}
                        <tr>
                            <td>{{mtg.date}}</td>
                            <td>{{mtg.holdout}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
    <div>
        <a href="{% url 'season:create_season' %}">Create Season</a>
    </div>
{% endblock %}